### ISSUE TITLE
feature request: adding an Makefile file

### ISSUE THREAD

**Issue by cmpxchg16b-nop** [septsea/strange-book-zero#1]
Consider adding an Makefile in your project root, so that people can build the target file(s) just by invoking a

```
make all
```

in the command-line.

**Comment by septsea** [comment]
Thank you for your advice. It sounds really interesting. I searched "makefile", but I didn't quite get it. (To be honest, math is a lot easier.) Actually, there are just two lines:

```shell
xelatex -synctex=1 -file-line-error main
xelatex -synctex=1 -file-line-error main
```

where `main` is the file name (without the extension name) of the main file.

Would you mind telling me how to write the Makefile file to run the two lines above?

Thanks.

**Comment by cmpxchg16b-nop** [comment]
Yes, I am happy that you replied at interested.

Basically, what a Makefile describe is a series of dependency relation, which's content might seems like:

```
final_target: dependent1 dependent2
    build_command --output final_target --from dependent1 dependent2 

dependent2: dependent3
    another_build_command_perhaps --output dependent2 --from dependent3
```

In mathematics, one might using `graph` to describe what people called `tree` in computing, a Makefile defined a dependency tree, the root is what you expect, or the final result of the entire building process, branch and leaf nodes are dependencies -- that's the prerequisites to build the what depends on them, e.g., the parent node, or the root node. 

A Makefile also defined how to build each target from its dependency(s), actually a target itself could also be a dependency to another target, like in the above example: the `dependent2` is a target, also a dependency of `final_target`, them, let's say we already got this Makefile is your project root dir, them once you invoke `make` in command-line, the `make` program will check if `final_target` exists, if not so, it will tries to build `final_target` using `dependent1` and `dependent2`, them `make` program will try to find `dependent2` in turns, if `dependent2` doesn't exists, it will try to build `dependent2` using `dependent3`, line(s) below each `{target}: [{dependent} ...]` are build command(s).

To help you grasp the concept of Makefile, let's do a simple experiment, first, we create some basic component files, imagine they are components of your project:

```
echo -n "hello" > hello.txt
echo -n "," > comma.txt
echo -n "w" > w.txt
echo -n "orld" > orld.txt
```
Now we have those files:

```
comma.txt hello.txt orld.txt  w.txt
```

Say we are trying to build a txt file with content "hello,world", how can we made that?

First, let's create an empty Makefile, them open it for writing:

```
touch Makefile
vi Makefile # or code Makefile
```

In Makefile, we could just simply type:

```
helloworld.txt: hello.txt comma.txt world.txt
	cat hello.txt comma.txt world.txt > helloworld.txt

world.txt: w.txt orld.txt
	cat w.txt orld.txt > world.txt
```

Then we save the file and exit, then run

```
make
```

in the command-line, you will see:

```
cat w.txt orld.txt > world.txt
cat hello.txt comma.txt world.txt > helloworld.txt
```

The `make` program just does what we expected it to.

**Comment by cmpxchg16b-nop** [comment]
As your question, please just try:

```
main.pdf: main.tex
	xelatex -interaction=nonstopmode -synctex=1 main.tex \
        xelatex -interaction=nonstopmode -synctex=1 main.tex

```

**Comment by septsea** [comment]
Thanks for your reply! I think I have understood the basic concepts of `Makefile`. I mainly use VSC, so I didn't realize the importance of a Makefile file.

Let me conclude the issue with an exclamation: almost all my fans are stronger than I am!

---

Well, this issue doesn't have to be closed.

**Comment by septsea** [comment]
Well.
